#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : fclones
Version  : 0.8.0
Release  : 2
URL      : file:///aot/build/clearlinux/packages/fclones/fclones-0.8.0.tar.gz
Source0  : file:///aot/build/clearlinux/packages/fclones/fclones-0.8.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: fclones-bin = %{version}-%{release}
Requires: pcre2
Requires: regex
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : grep
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : pcre2
BuildRequires : pkgconfig(libudev)
BuildRequires : regex
BuildRequires : rustc
BuildRequires : rustc-bin
BuildRequires : rustc-data
BuildRequires : rustc-dev
BuildRequires : rustc-staticdev
BuildRequires : termcolor
BuildRequires : time
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# FClones — Efficient Duplicate File Finder
[![CircleCI](https://circleci.com/gh/pkolaczk/fclones.svg?style=shield)](https://circleci.com/gh/pkolaczk/fclones)

%package bin
Summary: bin components for the fclones package.
Group: Binaries

%description bin
bin components for the fclones package.


%prep
%setup -q -n fclones
cd %{_builddir}/fclones

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
RUSTFLAGS="-C target-cpu=native"
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
cargo update --verbose

%install
RUSTFLAGS="-C target-cpu=native"
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
RUSTFLAGS="-C target-cpu=native" cargo install --verbose --no-track --path . --root %{buildroot}/usr/

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fclones
